// Code generated by go-swagger; DO NOT EDIT.

package oanda

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/torukita/go-oanda-api/models"
)

// GetAccountInstrumentsReader is a Reader for the GetAccountInstruments structure.
type GetAccountInstrumentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountInstrumentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccountInstrumentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAccountInstrumentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetAccountInstrumentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGetAccountInstrumentsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAccountInstrumentsOK creates a GetAccountInstrumentsOK with default headers values
func NewGetAccountInstrumentsOK() *GetAccountInstrumentsOK {
	return &GetAccountInstrumentsOK{}
}

/*GetAccountInstrumentsOK handles this case with default header values.

The list of tradeable instruments for the Account has been provided.
*/
type GetAccountInstrumentsOK struct {
	/*The unique identifier generated for the request
	 */
	RequestID string

	Payload *models.GetAccountInstrumentsOKBody
}

func (o *GetAccountInstrumentsOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountID}/instruments][%d] getAccountInstrumentsOK  %+v", 200, o.Payload)
}

func (o *GetAccountInstrumentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header RequestID
	o.RequestID = response.GetHeader("RequestID")

	o.Payload = new(models.GetAccountInstrumentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountInstrumentsBadRequest creates a GetAccountInstrumentsBadRequest with default headers values
func NewGetAccountInstrumentsBadRequest() *GetAccountInstrumentsBadRequest {
	return &GetAccountInstrumentsBadRequest{}
}

/*GetAccountInstrumentsBadRequest handles this case with default header values.

Bad Request. The client has provided invalid data to be processed by the server.
*/
type GetAccountInstrumentsBadRequest struct {
	/*The unique identifier generated for the request
	 */
	RequestID string

	Payload *models.GetAccountInstrumentsBadRequestBody
}

func (o *GetAccountInstrumentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountID}/instruments][%d] getAccountInstrumentsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAccountInstrumentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header RequestID
	o.RequestID = response.GetHeader("RequestID")

	o.Payload = new(models.GetAccountInstrumentsBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountInstrumentsUnauthorized creates a GetAccountInstrumentsUnauthorized with default headers values
func NewGetAccountInstrumentsUnauthorized() *GetAccountInstrumentsUnauthorized {
	return &GetAccountInstrumentsUnauthorized{}
}

/*GetAccountInstrumentsUnauthorized handles this case with default header values.

Unauthorized. The endpoint being access required the client to authenticated, however the the authentication token is invalid or has not been provided.
*/
type GetAccountInstrumentsUnauthorized struct {
	/*The unique identifier generated for the request
	 */
	RequestID string

	Payload *models.GetAccountInstrumentsUnauthorizedBody
}

func (o *GetAccountInstrumentsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountID}/instruments][%d] getAccountInstrumentsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetAccountInstrumentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header RequestID
	o.RequestID = response.GetHeader("RequestID")

	o.Payload = new(models.GetAccountInstrumentsUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountInstrumentsMethodNotAllowed creates a GetAccountInstrumentsMethodNotAllowed with default headers values
func NewGetAccountInstrumentsMethodNotAllowed() *GetAccountInstrumentsMethodNotAllowed {
	return &GetAccountInstrumentsMethodNotAllowed{}
}

/*GetAccountInstrumentsMethodNotAllowed handles this case with default header values.

Method Not Allowed. The client has attempted to access an endpoint using an HTTP method that is not supported.
*/
type GetAccountInstrumentsMethodNotAllowed struct {
	/*The unique identifier generated for the request
	 */
	RequestID string

	Payload *models.GetAccountInstrumentsMethodNotAllowedBody
}

func (o *GetAccountInstrumentsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /accounts/{accountID}/instruments][%d] getAccountInstrumentsMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *GetAccountInstrumentsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header RequestID
	o.RequestID = response.GetHeader("RequestID")

	o.Payload = new(models.GetAccountInstrumentsMethodNotAllowedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
