// Code generated by go-swagger; DO NOT EDIT.

package oanda

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStreamPricingParams creates a new StreamPricingParams object
// with the default values initialized.
func NewStreamPricingParams() *StreamPricingParams {
	var ()
	return &StreamPricingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStreamPricingParamsWithTimeout creates a new StreamPricingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStreamPricingParamsWithTimeout(timeout time.Duration) *StreamPricingParams {
	var ()
	return &StreamPricingParams{

		timeout: timeout,
	}
}

// NewStreamPricingParamsWithContext creates a new StreamPricingParams object
// with the default values initialized, and the ability to set a context for a request
func NewStreamPricingParamsWithContext(ctx context.Context) *StreamPricingParams {
	var ()
	return &StreamPricingParams{

		Context: ctx,
	}
}

// NewStreamPricingParamsWithHTTPClient creates a new StreamPricingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStreamPricingParamsWithHTTPClient(client *http.Client) *StreamPricingParams {
	var ()
	return &StreamPricingParams{
		HTTPClient: client,
	}
}

/*StreamPricingParams contains all the parameters to send to the API endpoint
for the stream pricing operation typically these are written to a http.Request
*/
type StreamPricingParams struct {

	/*AcceptDatetimeFormat
	  Format of DateTime fields in the request and response.

	*/
	AcceptDatetimeFormat *string
	/*Authorization
	  The authorization bearer token previously obtained by the client

	*/
	Authorization string
	/*AccountID
	  Account Identifier

	*/
	AccountID string
	/*Instruments
	  List of Instruments to stream Prices for.

	*/
	Instruments []string
	/*Snapshot
	  Flag that enables/disables the sending of a pricing snapshot when initially connecting to the stream.

	*/
	Snapshot *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stream pricing params
func (o *StreamPricingParams) WithTimeout(timeout time.Duration) *StreamPricingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stream pricing params
func (o *StreamPricingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stream pricing params
func (o *StreamPricingParams) WithContext(ctx context.Context) *StreamPricingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stream pricing params
func (o *StreamPricingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stream pricing params
func (o *StreamPricingParams) WithHTTPClient(client *http.Client) *StreamPricingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stream pricing params
func (o *StreamPricingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptDatetimeFormat adds the acceptDatetimeFormat to the stream pricing params
func (o *StreamPricingParams) WithAcceptDatetimeFormat(acceptDatetimeFormat *string) *StreamPricingParams {
	o.SetAcceptDatetimeFormat(acceptDatetimeFormat)
	return o
}

// SetAcceptDatetimeFormat adds the acceptDatetimeFormat to the stream pricing params
func (o *StreamPricingParams) SetAcceptDatetimeFormat(acceptDatetimeFormat *string) {
	o.AcceptDatetimeFormat = acceptDatetimeFormat
}

// WithAuthorization adds the authorization to the stream pricing params
func (o *StreamPricingParams) WithAuthorization(authorization string) *StreamPricingParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the stream pricing params
func (o *StreamPricingParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithAccountID adds the accountID to the stream pricing params
func (o *StreamPricingParams) WithAccountID(accountID string) *StreamPricingParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the stream pricing params
func (o *StreamPricingParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithInstruments adds the instruments to the stream pricing params
func (o *StreamPricingParams) WithInstruments(instruments []string) *StreamPricingParams {
	o.SetInstruments(instruments)
	return o
}

// SetInstruments adds the instruments to the stream pricing params
func (o *StreamPricingParams) SetInstruments(instruments []string) {
	o.Instruments = instruments
}

// WithSnapshot adds the snapshot to the stream pricing params
func (o *StreamPricingParams) WithSnapshot(snapshot *bool) *StreamPricingParams {
	o.SetSnapshot(snapshot)
	return o
}

// SetSnapshot adds the snapshot to the stream pricing params
func (o *StreamPricingParams) SetSnapshot(snapshot *bool) {
	o.Snapshot = snapshot
}

// WriteToRequest writes these params to a swagger request
func (o *StreamPricingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptDatetimeFormat != nil {

		// header param Accept-Datetime-Format
		if err := r.SetHeaderParam("Accept-Datetime-Format", *o.AcceptDatetimeFormat); err != nil {
			return err
		}

	}

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param accountID
	if err := r.SetPathParam("accountID", o.AccountID); err != nil {
		return err
	}

	valuesInstruments := o.Instruments

	joinedInstruments := swag.JoinByFormat(valuesInstruments, "csv")
	// query array param instruments
	if err := r.SetQueryParam("instruments", joinedInstruments...); err != nil {
		return err
	}

	if o.Snapshot != nil {

		// query param snapshot
		var qrSnapshot bool
		if o.Snapshot != nil {
			qrSnapshot = *o.Snapshot
		}
		qSnapshot := swag.FormatBool(qrSnapshot)
		if qSnapshot != "" {
			if err := r.SetQueryParam("snapshot", qSnapshot); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
