// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AccountProperties Properties related to an Account.
// swagger:model AccountProperties
type AccountProperties struct {

	// The Account's identifier
	ID string `json:"id,omitempty"`

	// The Account's associated MT4 Account ID. This field will not be present if the Account is not an MT4 account.
	Mt4AccountID int64 `json:"mt4AccountID,omitempty"`

	// The Account's tags
	Tags []string `json:"tags"`
}

// Validate validates this account properties
func (m *AccountProperties) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTags(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountProperties) validateTags(formats strfmt.Registry) error {

	if swag.IsZero(m.Tags) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountProperties) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountProperties) UnmarshalBinary(b []byte) error {
	var res AccountProperties
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
