// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ClientTag A client-provided tag that can contain any data and may be assigned to their Orders or Trades. Tags are typically used to associate groups of Trades and/or Orders together.
// swagger:model ClientTag
type ClientTag string

// Validate validates this client tag
func (m ClientTag) Validate(formats strfmt.Registry) error {
	return nil
}
