// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClientConfigureTransaction A ClientConfigureTransaction represents the configuration of an Account by a client.
// swagger:model ClientConfigureTransaction
type ClientConfigureTransaction struct {

	// The ID of the Account the Transaction was created for.
	AccountID string `json:"accountID,omitempty"`

	// The client-provided alias for the Account.
	Alias string `json:"alias,omitempty"`

	// The ID of the "batch" that the Transaction belongs to. Transactions in the same batch are applied to the Account simultaneously.
	BatchID string `json:"batchID,omitempty"`

	// The Transaction's Identifier.
	ID string `json:"id,omitempty"`

	// The margin rate override for the Account.
	MarginRate string `json:"marginRate,omitempty"`

	// The Request ID of the request which generated the transaction.
	RequestID string `json:"requestID,omitempty"`

	// The date/time when the Transaction was created.
	Time string `json:"time,omitempty"`

	// The Type of the Transaction. Always set to "CLIENT_CONFIGURE" in a ClientConfigureTransaction.
	Type string `json:"type,omitempty"`

	// The ID of the user that initiated the creation of the Transaction.
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this client configure transaction
func (m *ClientConfigureTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var clientConfigureTransactionTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CREATE","CLOSE","REOPEN","CLIENT_CONFIGURE","CLIENT_CONFIGURE_REJECT","TRANSFER_FUNDS","TRANSFER_FUNDS_REJECT","MARKET_ORDER","MARKET_ORDER_REJECT","LIMIT_ORDER","LIMIT_ORDER_REJECT","STOP_ORDER","STOP_ORDER_REJECT","MARKET_IF_TOUCHED_ORDER","MARKET_IF_TOUCHED_ORDER_REJECT","TAKE_PROFIT_ORDER","TAKE_PROFIT_ORDER_REJECT","STOP_LOSS_ORDER","STOP_LOSS_ORDER_REJECT","TRAILING_STOP_LOSS_ORDER","TRAILING_STOP_LOSS_ORDER_REJECT","ORDER_FILL","ORDER_CANCEL","ORDER_CANCEL_REJECT","ORDER_CLIENT_EXTENSIONS_MODIFY","ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT","TRADE_CLIENT_EXTENSIONS_MODIFY","TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT","MARGIN_CALL_ENTER","MARGIN_CALL_EXTEND","MARGIN_CALL_EXIT","DELAYED_TRADE_CLOSURE","DAILY_FINANCING","RESET_RESETTABLE_PL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clientConfigureTransactionTypeTypePropEnum = append(clientConfigureTransactionTypeTypePropEnum, v)
	}
}

const (
	// ClientConfigureTransactionTypeCREATE captures enum value "CREATE"
	ClientConfigureTransactionTypeCREATE string = "CREATE"
	// ClientConfigureTransactionTypeCLOSE captures enum value "CLOSE"
	ClientConfigureTransactionTypeCLOSE string = "CLOSE"
	// ClientConfigureTransactionTypeREOPEN captures enum value "REOPEN"
	ClientConfigureTransactionTypeREOPEN string = "REOPEN"
	// ClientConfigureTransactionTypeCLIENTCONFIGURE captures enum value "CLIENT_CONFIGURE"
	ClientConfigureTransactionTypeCLIENTCONFIGURE string = "CLIENT_CONFIGURE"
	// ClientConfigureTransactionTypeCLIENTCONFIGUREREJECT captures enum value "CLIENT_CONFIGURE_REJECT"
	ClientConfigureTransactionTypeCLIENTCONFIGUREREJECT string = "CLIENT_CONFIGURE_REJECT"
	// ClientConfigureTransactionTypeTRANSFERFUNDS captures enum value "TRANSFER_FUNDS"
	ClientConfigureTransactionTypeTRANSFERFUNDS string = "TRANSFER_FUNDS"
	// ClientConfigureTransactionTypeTRANSFERFUNDSREJECT captures enum value "TRANSFER_FUNDS_REJECT"
	ClientConfigureTransactionTypeTRANSFERFUNDSREJECT string = "TRANSFER_FUNDS_REJECT"
	// ClientConfigureTransactionTypeMARKETORDER captures enum value "MARKET_ORDER"
	ClientConfigureTransactionTypeMARKETORDER string = "MARKET_ORDER"
	// ClientConfigureTransactionTypeMARKETORDERREJECT captures enum value "MARKET_ORDER_REJECT"
	ClientConfigureTransactionTypeMARKETORDERREJECT string = "MARKET_ORDER_REJECT"
	// ClientConfigureTransactionTypeLIMITORDER captures enum value "LIMIT_ORDER"
	ClientConfigureTransactionTypeLIMITORDER string = "LIMIT_ORDER"
	// ClientConfigureTransactionTypeLIMITORDERREJECT captures enum value "LIMIT_ORDER_REJECT"
	ClientConfigureTransactionTypeLIMITORDERREJECT string = "LIMIT_ORDER_REJECT"
	// ClientConfigureTransactionTypeSTOPORDER captures enum value "STOP_ORDER"
	ClientConfigureTransactionTypeSTOPORDER string = "STOP_ORDER"
	// ClientConfigureTransactionTypeSTOPORDERREJECT captures enum value "STOP_ORDER_REJECT"
	ClientConfigureTransactionTypeSTOPORDERREJECT string = "STOP_ORDER_REJECT"
	// ClientConfigureTransactionTypeMARKETIFTOUCHEDORDER captures enum value "MARKET_IF_TOUCHED_ORDER"
	ClientConfigureTransactionTypeMARKETIFTOUCHEDORDER string = "MARKET_IF_TOUCHED_ORDER"
	// ClientConfigureTransactionTypeMARKETIFTOUCHEDORDERREJECT captures enum value "MARKET_IF_TOUCHED_ORDER_REJECT"
	ClientConfigureTransactionTypeMARKETIFTOUCHEDORDERREJECT string = "MARKET_IF_TOUCHED_ORDER_REJECT"
	// ClientConfigureTransactionTypeTAKEPROFITORDER captures enum value "TAKE_PROFIT_ORDER"
	ClientConfigureTransactionTypeTAKEPROFITORDER string = "TAKE_PROFIT_ORDER"
	// ClientConfigureTransactionTypeTAKEPROFITORDERREJECT captures enum value "TAKE_PROFIT_ORDER_REJECT"
	ClientConfigureTransactionTypeTAKEPROFITORDERREJECT string = "TAKE_PROFIT_ORDER_REJECT"
	// ClientConfigureTransactionTypeSTOPLOSSORDER captures enum value "STOP_LOSS_ORDER"
	ClientConfigureTransactionTypeSTOPLOSSORDER string = "STOP_LOSS_ORDER"
	// ClientConfigureTransactionTypeSTOPLOSSORDERREJECT captures enum value "STOP_LOSS_ORDER_REJECT"
	ClientConfigureTransactionTypeSTOPLOSSORDERREJECT string = "STOP_LOSS_ORDER_REJECT"
	// ClientConfigureTransactionTypeTRAILINGSTOPLOSSORDER captures enum value "TRAILING_STOP_LOSS_ORDER"
	ClientConfigureTransactionTypeTRAILINGSTOPLOSSORDER string = "TRAILING_STOP_LOSS_ORDER"
	// ClientConfigureTransactionTypeTRAILINGSTOPLOSSORDERREJECT captures enum value "TRAILING_STOP_LOSS_ORDER_REJECT"
	ClientConfigureTransactionTypeTRAILINGSTOPLOSSORDERREJECT string = "TRAILING_STOP_LOSS_ORDER_REJECT"
	// ClientConfigureTransactionTypeORDERFILL captures enum value "ORDER_FILL"
	ClientConfigureTransactionTypeORDERFILL string = "ORDER_FILL"
	// ClientConfigureTransactionTypeORDERCANCEL captures enum value "ORDER_CANCEL"
	ClientConfigureTransactionTypeORDERCANCEL string = "ORDER_CANCEL"
	// ClientConfigureTransactionTypeORDERCANCELREJECT captures enum value "ORDER_CANCEL_REJECT"
	ClientConfigureTransactionTypeORDERCANCELREJECT string = "ORDER_CANCEL_REJECT"
	// ClientConfigureTransactionTypeORDERCLIENTEXTENSIONSMODIFY captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY"
	ClientConfigureTransactionTypeORDERCLIENTEXTENSIONSMODIFY string = "ORDER_CLIENT_EXTENSIONS_MODIFY"
	// ClientConfigureTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	ClientConfigureTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT string = "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// ClientConfigureTransactionTypeTRADECLIENTEXTENSIONSMODIFY captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY"
	ClientConfigureTransactionTypeTRADECLIENTEXTENSIONSMODIFY string = "TRADE_CLIENT_EXTENSIONS_MODIFY"
	// ClientConfigureTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	ClientConfigureTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT string = "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// ClientConfigureTransactionTypeMARGINCALLENTER captures enum value "MARGIN_CALL_ENTER"
	ClientConfigureTransactionTypeMARGINCALLENTER string = "MARGIN_CALL_ENTER"
	// ClientConfigureTransactionTypeMARGINCALLEXTEND captures enum value "MARGIN_CALL_EXTEND"
	ClientConfigureTransactionTypeMARGINCALLEXTEND string = "MARGIN_CALL_EXTEND"
	// ClientConfigureTransactionTypeMARGINCALLEXIT captures enum value "MARGIN_CALL_EXIT"
	ClientConfigureTransactionTypeMARGINCALLEXIT string = "MARGIN_CALL_EXIT"
	// ClientConfigureTransactionTypeDELAYEDTRADECLOSURE captures enum value "DELAYED_TRADE_CLOSURE"
	ClientConfigureTransactionTypeDELAYEDTRADECLOSURE string = "DELAYED_TRADE_CLOSURE"
	// ClientConfigureTransactionTypeDAILYFINANCING captures enum value "DAILY_FINANCING"
	ClientConfigureTransactionTypeDAILYFINANCING string = "DAILY_FINANCING"
	// ClientConfigureTransactionTypeRESETRESETTABLEPL captures enum value "RESET_RESETTABLE_PL"
	ClientConfigureTransactionTypeRESETRESETTABLEPL string = "RESET_RESETTABLE_PL"
)

// prop value enum
func (m *ClientConfigureTransaction) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, clientConfigureTransactionTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ClientConfigureTransaction) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClientConfigureTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClientConfigureTransaction) UnmarshalBinary(b []byte) error {
	var res ClientConfigureTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
