// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CloseTradeBadRequestBody close trade bad request body
// swagger:model closeTradeBadRequestBody
type CloseTradeBadRequestBody struct {

	// The code of the error that has occurred. This field may not be returned for some errors.
	ErrorCode string `json:"errorCode,omitempty"`

	// The human-readable description of the error that has occurred.
	ErrorMessage string `json:"errorMessage,omitempty"`

	// order reject transaction
	OrderRejectTransaction *MarketOrderRejectTransaction `json:"orderRejectTransaction,omitempty"`
}

// Validate validates this close trade bad request body
func (m *CloseTradeBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderRejectTransaction(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CloseTradeBadRequestBody) validateOrderRejectTransaction(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderRejectTransaction) { // not required
		return nil
	}

	if m.OrderRejectTransaction != nil {

		if err := m.OrderRejectTransaction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("orderRejectTransaction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CloseTradeBadRequestBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloseTradeBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CloseTradeBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
