// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Currency Currency name identifier. Used by clients to refer to currencies.
// swagger:model Currency
type Currency string

// Validate validates this currency
func (m Currency) Validate(formats strfmt.Registry) error {
	return nil
}
