// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// DecimalNumber The string representation of a decimal number.
// swagger:model DecimalNumber
type DecimalNumber string

// Validate validates this decimal number
func (m DecimalNumber) Validate(formats strfmt.Registry) error {
	return nil
}
