// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DelayedTradeClosureTransaction A DelayedTradeClosure Transaction is created administratively to indicate open trades that should have been closed but weren't because the open trades' instruments were untradeable at the time. Open trades listed in this transaction will be closed once their respective instruments become tradeable.
// swagger:model DelayedTradeClosureTransaction
type DelayedTradeClosureTransaction struct {

	// The ID of the Account the Transaction was created for.
	AccountID string `json:"accountID,omitempty"`

	// The ID of the "batch" that the Transaction belongs to. Transactions in the same batch are applied to the Account simultaneously.
	BatchID string `json:"batchID,omitempty"`

	// The Transaction's Identifier.
	ID string `json:"id,omitempty"`

	// The reason for the delayed trade closure
	Reason string `json:"reason,omitempty"`

	// The Request ID of the request which generated the transaction.
	RequestID string `json:"requestID,omitempty"`

	// The date/time when the Transaction was created.
	Time string `json:"time,omitempty"`

	// List of Trade ID's identifying the open trades that will be closed when their respective instruments become tradeable
	TradeIds string `json:"tradeIDs,omitempty"`

	// The Type of the Transaction. Always set to "DELAYED_TRADE_CLOSURE" for an DelayedTradeClosureTransaction.
	Type string `json:"type,omitempty"`

	// The ID of the user that initiated the creation of the Transaction.
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this delayed trade closure transaction
func (m *DelayedTradeClosureTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var delayedTradeClosureTransactionTypeReasonPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CLIENT_ORDER","TRADE_CLOSE","POSITION_CLOSEOUT","MARGIN_CLOSEOUT","DELAYED_TRADE_CLOSE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		delayedTradeClosureTransactionTypeReasonPropEnum = append(delayedTradeClosureTransactionTypeReasonPropEnum, v)
	}
}

const (
	// DelayedTradeClosureTransactionReasonCLIENTORDER captures enum value "CLIENT_ORDER"
	DelayedTradeClosureTransactionReasonCLIENTORDER string = "CLIENT_ORDER"
	// DelayedTradeClosureTransactionReasonTRADECLOSE captures enum value "TRADE_CLOSE"
	DelayedTradeClosureTransactionReasonTRADECLOSE string = "TRADE_CLOSE"
	// DelayedTradeClosureTransactionReasonPOSITIONCLOSEOUT captures enum value "POSITION_CLOSEOUT"
	DelayedTradeClosureTransactionReasonPOSITIONCLOSEOUT string = "POSITION_CLOSEOUT"
	// DelayedTradeClosureTransactionReasonMARGINCLOSEOUT captures enum value "MARGIN_CLOSEOUT"
	DelayedTradeClosureTransactionReasonMARGINCLOSEOUT string = "MARGIN_CLOSEOUT"
	// DelayedTradeClosureTransactionReasonDELAYEDTRADECLOSE captures enum value "DELAYED_TRADE_CLOSE"
	DelayedTradeClosureTransactionReasonDELAYEDTRADECLOSE string = "DELAYED_TRADE_CLOSE"
)

// prop value enum
func (m *DelayedTradeClosureTransaction) validateReasonEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, delayedTradeClosureTransactionTypeReasonPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DelayedTradeClosureTransaction) validateReason(formats strfmt.Registry) error {

	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	// value enum
	if err := m.validateReasonEnum("reason", "body", m.Reason); err != nil {
		return err
	}

	return nil
}

var delayedTradeClosureTransactionTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CREATE","CLOSE","REOPEN","CLIENT_CONFIGURE","CLIENT_CONFIGURE_REJECT","TRANSFER_FUNDS","TRANSFER_FUNDS_REJECT","MARKET_ORDER","MARKET_ORDER_REJECT","LIMIT_ORDER","LIMIT_ORDER_REJECT","STOP_ORDER","STOP_ORDER_REJECT","MARKET_IF_TOUCHED_ORDER","MARKET_IF_TOUCHED_ORDER_REJECT","TAKE_PROFIT_ORDER","TAKE_PROFIT_ORDER_REJECT","STOP_LOSS_ORDER","STOP_LOSS_ORDER_REJECT","TRAILING_STOP_LOSS_ORDER","TRAILING_STOP_LOSS_ORDER_REJECT","ORDER_FILL","ORDER_CANCEL","ORDER_CANCEL_REJECT","ORDER_CLIENT_EXTENSIONS_MODIFY","ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT","TRADE_CLIENT_EXTENSIONS_MODIFY","TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT","MARGIN_CALL_ENTER","MARGIN_CALL_EXTEND","MARGIN_CALL_EXIT","DELAYED_TRADE_CLOSURE","DAILY_FINANCING","RESET_RESETTABLE_PL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		delayedTradeClosureTransactionTypeTypePropEnum = append(delayedTradeClosureTransactionTypeTypePropEnum, v)
	}
}

const (
	// DelayedTradeClosureTransactionTypeCREATE captures enum value "CREATE"
	DelayedTradeClosureTransactionTypeCREATE string = "CREATE"
	// DelayedTradeClosureTransactionTypeCLOSE captures enum value "CLOSE"
	DelayedTradeClosureTransactionTypeCLOSE string = "CLOSE"
	// DelayedTradeClosureTransactionTypeREOPEN captures enum value "REOPEN"
	DelayedTradeClosureTransactionTypeREOPEN string = "REOPEN"
	// DelayedTradeClosureTransactionTypeCLIENTCONFIGURE captures enum value "CLIENT_CONFIGURE"
	DelayedTradeClosureTransactionTypeCLIENTCONFIGURE string = "CLIENT_CONFIGURE"
	// DelayedTradeClosureTransactionTypeCLIENTCONFIGUREREJECT captures enum value "CLIENT_CONFIGURE_REJECT"
	DelayedTradeClosureTransactionTypeCLIENTCONFIGUREREJECT string = "CLIENT_CONFIGURE_REJECT"
	// DelayedTradeClosureTransactionTypeTRANSFERFUNDS captures enum value "TRANSFER_FUNDS"
	DelayedTradeClosureTransactionTypeTRANSFERFUNDS string = "TRANSFER_FUNDS"
	// DelayedTradeClosureTransactionTypeTRANSFERFUNDSREJECT captures enum value "TRANSFER_FUNDS_REJECT"
	DelayedTradeClosureTransactionTypeTRANSFERFUNDSREJECT string = "TRANSFER_FUNDS_REJECT"
	// DelayedTradeClosureTransactionTypeMARKETORDER captures enum value "MARKET_ORDER"
	DelayedTradeClosureTransactionTypeMARKETORDER string = "MARKET_ORDER"
	// DelayedTradeClosureTransactionTypeMARKETORDERREJECT captures enum value "MARKET_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeMARKETORDERREJECT string = "MARKET_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeLIMITORDER captures enum value "LIMIT_ORDER"
	DelayedTradeClosureTransactionTypeLIMITORDER string = "LIMIT_ORDER"
	// DelayedTradeClosureTransactionTypeLIMITORDERREJECT captures enum value "LIMIT_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeLIMITORDERREJECT string = "LIMIT_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeSTOPORDER captures enum value "STOP_ORDER"
	DelayedTradeClosureTransactionTypeSTOPORDER string = "STOP_ORDER"
	// DelayedTradeClosureTransactionTypeSTOPORDERREJECT captures enum value "STOP_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeSTOPORDERREJECT string = "STOP_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeMARKETIFTOUCHEDORDER captures enum value "MARKET_IF_TOUCHED_ORDER"
	DelayedTradeClosureTransactionTypeMARKETIFTOUCHEDORDER string = "MARKET_IF_TOUCHED_ORDER"
	// DelayedTradeClosureTransactionTypeMARKETIFTOUCHEDORDERREJECT captures enum value "MARKET_IF_TOUCHED_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeMARKETIFTOUCHEDORDERREJECT string = "MARKET_IF_TOUCHED_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeTAKEPROFITORDER captures enum value "TAKE_PROFIT_ORDER"
	DelayedTradeClosureTransactionTypeTAKEPROFITORDER string = "TAKE_PROFIT_ORDER"
	// DelayedTradeClosureTransactionTypeTAKEPROFITORDERREJECT captures enum value "TAKE_PROFIT_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeTAKEPROFITORDERREJECT string = "TAKE_PROFIT_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeSTOPLOSSORDER captures enum value "STOP_LOSS_ORDER"
	DelayedTradeClosureTransactionTypeSTOPLOSSORDER string = "STOP_LOSS_ORDER"
	// DelayedTradeClosureTransactionTypeSTOPLOSSORDERREJECT captures enum value "STOP_LOSS_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeSTOPLOSSORDERREJECT string = "STOP_LOSS_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeTRAILINGSTOPLOSSORDER captures enum value "TRAILING_STOP_LOSS_ORDER"
	DelayedTradeClosureTransactionTypeTRAILINGSTOPLOSSORDER string = "TRAILING_STOP_LOSS_ORDER"
	// DelayedTradeClosureTransactionTypeTRAILINGSTOPLOSSORDERREJECT captures enum value "TRAILING_STOP_LOSS_ORDER_REJECT"
	DelayedTradeClosureTransactionTypeTRAILINGSTOPLOSSORDERREJECT string = "TRAILING_STOP_LOSS_ORDER_REJECT"
	// DelayedTradeClosureTransactionTypeORDERFILL captures enum value "ORDER_FILL"
	DelayedTradeClosureTransactionTypeORDERFILL string = "ORDER_FILL"
	// DelayedTradeClosureTransactionTypeORDERCANCEL captures enum value "ORDER_CANCEL"
	DelayedTradeClosureTransactionTypeORDERCANCEL string = "ORDER_CANCEL"
	// DelayedTradeClosureTransactionTypeORDERCANCELREJECT captures enum value "ORDER_CANCEL_REJECT"
	DelayedTradeClosureTransactionTypeORDERCANCELREJECT string = "ORDER_CANCEL_REJECT"
	// DelayedTradeClosureTransactionTypeORDERCLIENTEXTENSIONSMODIFY captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY"
	DelayedTradeClosureTransactionTypeORDERCLIENTEXTENSIONSMODIFY string = "ORDER_CLIENT_EXTENSIONS_MODIFY"
	// DelayedTradeClosureTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	DelayedTradeClosureTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT string = "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// DelayedTradeClosureTransactionTypeTRADECLIENTEXTENSIONSMODIFY captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY"
	DelayedTradeClosureTransactionTypeTRADECLIENTEXTENSIONSMODIFY string = "TRADE_CLIENT_EXTENSIONS_MODIFY"
	// DelayedTradeClosureTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	DelayedTradeClosureTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT string = "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// DelayedTradeClosureTransactionTypeMARGINCALLENTER captures enum value "MARGIN_CALL_ENTER"
	DelayedTradeClosureTransactionTypeMARGINCALLENTER string = "MARGIN_CALL_ENTER"
	// DelayedTradeClosureTransactionTypeMARGINCALLEXTEND captures enum value "MARGIN_CALL_EXTEND"
	DelayedTradeClosureTransactionTypeMARGINCALLEXTEND string = "MARGIN_CALL_EXTEND"
	// DelayedTradeClosureTransactionTypeMARGINCALLEXIT captures enum value "MARGIN_CALL_EXIT"
	DelayedTradeClosureTransactionTypeMARGINCALLEXIT string = "MARGIN_CALL_EXIT"
	// DelayedTradeClosureTransactionTypeDELAYEDTRADECLOSURE captures enum value "DELAYED_TRADE_CLOSURE"
	DelayedTradeClosureTransactionTypeDELAYEDTRADECLOSURE string = "DELAYED_TRADE_CLOSURE"
	// DelayedTradeClosureTransactionTypeDAILYFINANCING captures enum value "DAILY_FINANCING"
	DelayedTradeClosureTransactionTypeDAILYFINANCING string = "DAILY_FINANCING"
	// DelayedTradeClosureTransactionTypeRESETRESETTABLEPL captures enum value "RESET_RESETTABLE_PL"
	DelayedTradeClosureTransactionTypeRESETRESETTABLEPL string = "RESET_RESETTABLE_PL"
)

// prop value enum
func (m *DelayedTradeClosureTransaction) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, delayedTradeClosureTransactionTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DelayedTradeClosureTransaction) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DelayedTradeClosureTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DelayedTradeClosureTransaction) UnmarshalBinary(b []byte) error {
	var res DelayedTradeClosureTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
