// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetInstrumentsInstrumentPositionBookOKBody get instruments instrument position book o k body
// swagger:model getInstrumentsInstrumentPositionBookOKBody
type GetInstrumentsInstrumentPositionBookOKBody struct {

	// position book
	PositionBook *PositionBook `json:"positionBook,omitempty"`
}

// Validate validates this get instruments instrument position book o k body
func (m *GetInstrumentsInstrumentPositionBookOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePositionBook(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetInstrumentsInstrumentPositionBookOKBody) validatePositionBook(formats strfmt.Registry) error {

	if swag.IsZero(m.PositionBook) { // not required
		return nil
	}

	if m.PositionBook != nil {

		if err := m.PositionBook.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("positionBook")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetInstrumentsInstrumentPositionBookOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetInstrumentsInstrumentPositionBookOKBody) UnmarshalBinary(b []byte) error {
	var res GetInstrumentsInstrumentPositionBookOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
