// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LimitOrderRequest A LimitOrderRequest specifies the parameters that may be set when creating a Limit Order.
// swagger:model LimitOrderRequest
type LimitOrderRequest struct {

	// client extensions
	ClientExtensions *ClientExtensions `json:"clientExtensions,omitempty"`

	// The date/time when the Limit Order will be cancelled if its timeInForce is "GTD".
	GtdTime string `json:"gtdTime,omitempty"`

	// The Limit Order's Instrument.
	Instrument string `json:"instrument,omitempty"`

	// Specification of how Positions in the Account are modified when the Order is filled.
	PositionFill string `json:"positionFill,omitempty"`

	// The price threshold specified for the Limit Order. The Limit Order will only be filled by a market price that is equal to or better than this price.
	Price string `json:"price,omitempty"`

	// stop loss on fill
	StopLossOnFill *StopLossDetails `json:"stopLossOnFill,omitempty"`

	// take profit on fill
	TakeProfitOnFill *TakeProfitDetails `json:"takeProfitOnFill,omitempty"`

	// The time-in-force requested for the Limit Order.
	TimeInForce string `json:"timeInForce,omitempty"`

	// trade client extensions
	TradeClientExtensions *ClientExtensions `json:"tradeClientExtensions,omitempty"`

	// trailing stop loss on fill
	TrailingStopLossOnFill *TrailingStopLossDetails `json:"trailingStopLossOnFill,omitempty"`

	// Specification of what component of a price should be used for comparison when determining if the Order should be filled.
	TriggerCondition string `json:"triggerCondition,omitempty"`

	// The type of the Order to Create. Must be set to "LIMIT" when creating a Market Order.
	Type string `json:"type,omitempty"`

	// The quantity requested to be filled by the Limit Order. A posititive number of units results in a long Order, and a negative number of units results in a short Order.
	Units string `json:"units,omitempty"`
}

// Validate validates this limit order request
func (m *LimitOrderRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientExtensions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePositionFill(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStopLossOnFill(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTakeProfitOnFill(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTimeInForce(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTradeClientExtensions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTrailingStopLossOnFill(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTriggerCondition(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LimitOrderRequest) validateClientExtensions(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientExtensions) { // not required
		return nil
	}

	if m.ClientExtensions != nil {

		if err := m.ClientExtensions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clientExtensions")
			}
			return err
		}
	}

	return nil
}

var limitOrderRequestTypePositionFillPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OPEN_ONLY","REDUCE_FIRST","REDUCE_ONLY","DEFAULT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		limitOrderRequestTypePositionFillPropEnum = append(limitOrderRequestTypePositionFillPropEnum, v)
	}
}

const (
	// LimitOrderRequestPositionFillOPENONLY captures enum value "OPEN_ONLY"
	LimitOrderRequestPositionFillOPENONLY string = "OPEN_ONLY"
	// LimitOrderRequestPositionFillREDUCEFIRST captures enum value "REDUCE_FIRST"
	LimitOrderRequestPositionFillREDUCEFIRST string = "REDUCE_FIRST"
	// LimitOrderRequestPositionFillREDUCEONLY captures enum value "REDUCE_ONLY"
	LimitOrderRequestPositionFillREDUCEONLY string = "REDUCE_ONLY"
	// LimitOrderRequestPositionFillDEFAULT captures enum value "DEFAULT"
	LimitOrderRequestPositionFillDEFAULT string = "DEFAULT"
)

// prop value enum
func (m *LimitOrderRequest) validatePositionFillEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, limitOrderRequestTypePositionFillPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LimitOrderRequest) validatePositionFill(formats strfmt.Registry) error {

	if swag.IsZero(m.PositionFill) { // not required
		return nil
	}

	// value enum
	if err := m.validatePositionFillEnum("positionFill", "body", m.PositionFill); err != nil {
		return err
	}

	return nil
}

func (m *LimitOrderRequest) validateStopLossOnFill(formats strfmt.Registry) error {

	if swag.IsZero(m.StopLossOnFill) { // not required
		return nil
	}

	if m.StopLossOnFill != nil {

		if err := m.StopLossOnFill.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stopLossOnFill")
			}
			return err
		}
	}

	return nil
}

func (m *LimitOrderRequest) validateTakeProfitOnFill(formats strfmt.Registry) error {

	if swag.IsZero(m.TakeProfitOnFill) { // not required
		return nil
	}

	if m.TakeProfitOnFill != nil {

		if err := m.TakeProfitOnFill.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("takeProfitOnFill")
			}
			return err
		}
	}

	return nil
}

var limitOrderRequestTypeTimeInForcePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["GTC","GTD","GFD","FOK","IOC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		limitOrderRequestTypeTimeInForcePropEnum = append(limitOrderRequestTypeTimeInForcePropEnum, v)
	}
}

const (
	// LimitOrderRequestTimeInForceGTC captures enum value "GTC"
	LimitOrderRequestTimeInForceGTC string = "GTC"
	// LimitOrderRequestTimeInForceGTD captures enum value "GTD"
	LimitOrderRequestTimeInForceGTD string = "GTD"
	// LimitOrderRequestTimeInForceGFD captures enum value "GFD"
	LimitOrderRequestTimeInForceGFD string = "GFD"
	// LimitOrderRequestTimeInForceFOK captures enum value "FOK"
	LimitOrderRequestTimeInForceFOK string = "FOK"
	// LimitOrderRequestTimeInForceIOC captures enum value "IOC"
	LimitOrderRequestTimeInForceIOC string = "IOC"
)

// prop value enum
func (m *LimitOrderRequest) validateTimeInForceEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, limitOrderRequestTypeTimeInForcePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LimitOrderRequest) validateTimeInForce(formats strfmt.Registry) error {

	if swag.IsZero(m.TimeInForce) { // not required
		return nil
	}

	// value enum
	if err := m.validateTimeInForceEnum("timeInForce", "body", m.TimeInForce); err != nil {
		return err
	}

	return nil
}

func (m *LimitOrderRequest) validateTradeClientExtensions(formats strfmt.Registry) error {

	if swag.IsZero(m.TradeClientExtensions) { // not required
		return nil
	}

	if m.TradeClientExtensions != nil {

		if err := m.TradeClientExtensions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tradeClientExtensions")
			}
			return err
		}
	}

	return nil
}

func (m *LimitOrderRequest) validateTrailingStopLossOnFill(formats strfmt.Registry) error {

	if swag.IsZero(m.TrailingStopLossOnFill) { // not required
		return nil
	}

	if m.TrailingStopLossOnFill != nil {

		if err := m.TrailingStopLossOnFill.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("trailingStopLossOnFill")
			}
			return err
		}
	}

	return nil
}

var limitOrderRequestTypeTriggerConditionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DEFAULT","INVERSE","BID","ASK","MID"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		limitOrderRequestTypeTriggerConditionPropEnum = append(limitOrderRequestTypeTriggerConditionPropEnum, v)
	}
}

const (
	// LimitOrderRequestTriggerConditionDEFAULT captures enum value "DEFAULT"
	LimitOrderRequestTriggerConditionDEFAULT string = "DEFAULT"
	// LimitOrderRequestTriggerConditionINVERSE captures enum value "INVERSE"
	LimitOrderRequestTriggerConditionINVERSE string = "INVERSE"
	// LimitOrderRequestTriggerConditionBID captures enum value "BID"
	LimitOrderRequestTriggerConditionBID string = "BID"
	// LimitOrderRequestTriggerConditionASK captures enum value "ASK"
	LimitOrderRequestTriggerConditionASK string = "ASK"
	// LimitOrderRequestTriggerConditionMID captures enum value "MID"
	LimitOrderRequestTriggerConditionMID string = "MID"
)

// prop value enum
func (m *LimitOrderRequest) validateTriggerConditionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, limitOrderRequestTypeTriggerConditionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LimitOrderRequest) validateTriggerCondition(formats strfmt.Registry) error {

	if swag.IsZero(m.TriggerCondition) { // not required
		return nil
	}

	// value enum
	if err := m.validateTriggerConditionEnum("triggerCondition", "body", m.TriggerCondition); err != nil {
		return err
	}

	return nil
}

var limitOrderRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MARKET","LIMIT","STOP","MARKET_IF_TOUCHED","TAKE_PROFIT","STOP_LOSS","TRAILING_STOP_LOSS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		limitOrderRequestTypeTypePropEnum = append(limitOrderRequestTypeTypePropEnum, v)
	}
}

const (
	// LimitOrderRequestTypeMARKET captures enum value "MARKET"
	LimitOrderRequestTypeMARKET string = "MARKET"
	// LimitOrderRequestTypeLIMIT captures enum value "LIMIT"
	LimitOrderRequestTypeLIMIT string = "LIMIT"
	// LimitOrderRequestTypeSTOP captures enum value "STOP"
	LimitOrderRequestTypeSTOP string = "STOP"
	// LimitOrderRequestTypeMARKETIFTOUCHED captures enum value "MARKET_IF_TOUCHED"
	LimitOrderRequestTypeMARKETIFTOUCHED string = "MARKET_IF_TOUCHED"
	// LimitOrderRequestTypeTAKEPROFIT captures enum value "TAKE_PROFIT"
	LimitOrderRequestTypeTAKEPROFIT string = "TAKE_PROFIT"
	// LimitOrderRequestTypeSTOPLOSS captures enum value "STOP_LOSS"
	LimitOrderRequestTypeSTOPLOSS string = "STOP_LOSS"
	// LimitOrderRequestTypeTRAILINGSTOPLOSS captures enum value "TRAILING_STOP_LOSS"
	LimitOrderRequestTypeTRAILINGSTOPLOSS string = "TRAILING_STOP_LOSS"
)

// prop value enum
func (m *LimitOrderRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, limitOrderRequestTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LimitOrderRequest) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LimitOrderRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LimitOrderRequest) UnmarshalBinary(b []byte) error {
	var res LimitOrderRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
