// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderClientExtensionsModifyTransaction A OrderClientExtensionsModifyTransaction represents the modification of an Order's Client Extensions.
// swagger:model OrderClientExtensionsModifyTransaction
type OrderClientExtensionsModifyTransaction struct {

	// The ID of the Account the Transaction was created for.
	AccountID string `json:"accountID,omitempty"`

	// The ID of the "batch" that the Transaction belongs to. Transactions in the same batch are applied to the Account simultaneously.
	BatchID string `json:"batchID,omitempty"`

	// client extensions modify
	ClientExtensionsModify *ClientExtensions `json:"clientExtensionsModify,omitempty"`

	// The original Client ID of the Order who's client extensions are to be modified.
	ClientOrderID string `json:"clientOrderID,omitempty"`

	// The Transaction's Identifier.
	ID string `json:"id,omitempty"`

	// The ID of the Order who's client extensions are to be modified.
	OrderID string `json:"orderID,omitempty"`

	// The Request ID of the request which generated the transaction.
	RequestID string `json:"requestID,omitempty"`

	// The date/time when the Transaction was created.
	Time string `json:"time,omitempty"`

	// trade client extensions modify
	TradeClientExtensionsModify *ClientExtensions `json:"tradeClientExtensionsModify,omitempty"`

	// The Type of the Transaction. Always set to "ORDER_CLIENT_EXTENSIONS_MODIFY" for a OrderClienteExtensionsModifyTransaction.
	Type string `json:"type,omitempty"`

	// The ID of the user that initiated the creation of the Transaction.
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this order client extensions modify transaction
func (m *OrderClientExtensionsModifyTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientExtensionsModify(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTradeClientExtensionsModify(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderClientExtensionsModifyTransaction) validateClientExtensionsModify(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientExtensionsModify) { // not required
		return nil
	}

	if m.ClientExtensionsModify != nil {

		if err := m.ClientExtensionsModify.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clientExtensionsModify")
			}
			return err
		}
	}

	return nil
}

func (m *OrderClientExtensionsModifyTransaction) validateTradeClientExtensionsModify(formats strfmt.Registry) error {

	if swag.IsZero(m.TradeClientExtensionsModify) { // not required
		return nil
	}

	if m.TradeClientExtensionsModify != nil {

		if err := m.TradeClientExtensionsModify.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tradeClientExtensionsModify")
			}
			return err
		}
	}

	return nil
}

var orderClientExtensionsModifyTransactionTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["CREATE","CLOSE","REOPEN","CLIENT_CONFIGURE","CLIENT_CONFIGURE_REJECT","TRANSFER_FUNDS","TRANSFER_FUNDS_REJECT","MARKET_ORDER","MARKET_ORDER_REJECT","LIMIT_ORDER","LIMIT_ORDER_REJECT","STOP_ORDER","STOP_ORDER_REJECT","MARKET_IF_TOUCHED_ORDER","MARKET_IF_TOUCHED_ORDER_REJECT","TAKE_PROFIT_ORDER","TAKE_PROFIT_ORDER_REJECT","STOP_LOSS_ORDER","STOP_LOSS_ORDER_REJECT","TRAILING_STOP_LOSS_ORDER","TRAILING_STOP_LOSS_ORDER_REJECT","ORDER_FILL","ORDER_CANCEL","ORDER_CANCEL_REJECT","ORDER_CLIENT_EXTENSIONS_MODIFY","ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT","TRADE_CLIENT_EXTENSIONS_MODIFY","TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT","MARGIN_CALL_ENTER","MARGIN_CALL_EXTEND","MARGIN_CALL_EXIT","DELAYED_TRADE_CLOSURE","DAILY_FINANCING","RESET_RESETTABLE_PL"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderClientExtensionsModifyTransactionTypeTypePropEnum = append(orderClientExtensionsModifyTransactionTypeTypePropEnum, v)
	}
}

const (
	// OrderClientExtensionsModifyTransactionTypeCREATE captures enum value "CREATE"
	OrderClientExtensionsModifyTransactionTypeCREATE string = "CREATE"
	// OrderClientExtensionsModifyTransactionTypeCLOSE captures enum value "CLOSE"
	OrderClientExtensionsModifyTransactionTypeCLOSE string = "CLOSE"
	// OrderClientExtensionsModifyTransactionTypeREOPEN captures enum value "REOPEN"
	OrderClientExtensionsModifyTransactionTypeREOPEN string = "REOPEN"
	// OrderClientExtensionsModifyTransactionTypeCLIENTCONFIGURE captures enum value "CLIENT_CONFIGURE"
	OrderClientExtensionsModifyTransactionTypeCLIENTCONFIGURE string = "CLIENT_CONFIGURE"
	// OrderClientExtensionsModifyTransactionTypeCLIENTCONFIGUREREJECT captures enum value "CLIENT_CONFIGURE_REJECT"
	OrderClientExtensionsModifyTransactionTypeCLIENTCONFIGUREREJECT string = "CLIENT_CONFIGURE_REJECT"
	// OrderClientExtensionsModifyTransactionTypeTRANSFERFUNDS captures enum value "TRANSFER_FUNDS"
	OrderClientExtensionsModifyTransactionTypeTRANSFERFUNDS string = "TRANSFER_FUNDS"
	// OrderClientExtensionsModifyTransactionTypeTRANSFERFUNDSREJECT captures enum value "TRANSFER_FUNDS_REJECT"
	OrderClientExtensionsModifyTransactionTypeTRANSFERFUNDSREJECT string = "TRANSFER_FUNDS_REJECT"
	// OrderClientExtensionsModifyTransactionTypeMARKETORDER captures enum value "MARKET_ORDER"
	OrderClientExtensionsModifyTransactionTypeMARKETORDER string = "MARKET_ORDER"
	// OrderClientExtensionsModifyTransactionTypeMARKETORDERREJECT captures enum value "MARKET_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeMARKETORDERREJECT string = "MARKET_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeLIMITORDER captures enum value "LIMIT_ORDER"
	OrderClientExtensionsModifyTransactionTypeLIMITORDER string = "LIMIT_ORDER"
	// OrderClientExtensionsModifyTransactionTypeLIMITORDERREJECT captures enum value "LIMIT_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeLIMITORDERREJECT string = "LIMIT_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeSTOPORDER captures enum value "STOP_ORDER"
	OrderClientExtensionsModifyTransactionTypeSTOPORDER string = "STOP_ORDER"
	// OrderClientExtensionsModifyTransactionTypeSTOPORDERREJECT captures enum value "STOP_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeSTOPORDERREJECT string = "STOP_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeMARKETIFTOUCHEDORDER captures enum value "MARKET_IF_TOUCHED_ORDER"
	OrderClientExtensionsModifyTransactionTypeMARKETIFTOUCHEDORDER string = "MARKET_IF_TOUCHED_ORDER"
	// OrderClientExtensionsModifyTransactionTypeMARKETIFTOUCHEDORDERREJECT captures enum value "MARKET_IF_TOUCHED_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeMARKETIFTOUCHEDORDERREJECT string = "MARKET_IF_TOUCHED_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeTAKEPROFITORDER captures enum value "TAKE_PROFIT_ORDER"
	OrderClientExtensionsModifyTransactionTypeTAKEPROFITORDER string = "TAKE_PROFIT_ORDER"
	// OrderClientExtensionsModifyTransactionTypeTAKEPROFITORDERREJECT captures enum value "TAKE_PROFIT_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeTAKEPROFITORDERREJECT string = "TAKE_PROFIT_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeSTOPLOSSORDER captures enum value "STOP_LOSS_ORDER"
	OrderClientExtensionsModifyTransactionTypeSTOPLOSSORDER string = "STOP_LOSS_ORDER"
	// OrderClientExtensionsModifyTransactionTypeSTOPLOSSORDERREJECT captures enum value "STOP_LOSS_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeSTOPLOSSORDERREJECT string = "STOP_LOSS_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeTRAILINGSTOPLOSSORDER captures enum value "TRAILING_STOP_LOSS_ORDER"
	OrderClientExtensionsModifyTransactionTypeTRAILINGSTOPLOSSORDER string = "TRAILING_STOP_LOSS_ORDER"
	// OrderClientExtensionsModifyTransactionTypeTRAILINGSTOPLOSSORDERREJECT captures enum value "TRAILING_STOP_LOSS_ORDER_REJECT"
	OrderClientExtensionsModifyTransactionTypeTRAILINGSTOPLOSSORDERREJECT string = "TRAILING_STOP_LOSS_ORDER_REJECT"
	// OrderClientExtensionsModifyTransactionTypeORDERFILL captures enum value "ORDER_FILL"
	OrderClientExtensionsModifyTransactionTypeORDERFILL string = "ORDER_FILL"
	// OrderClientExtensionsModifyTransactionTypeORDERCANCEL captures enum value "ORDER_CANCEL"
	OrderClientExtensionsModifyTransactionTypeORDERCANCEL string = "ORDER_CANCEL"
	// OrderClientExtensionsModifyTransactionTypeORDERCANCELREJECT captures enum value "ORDER_CANCEL_REJECT"
	OrderClientExtensionsModifyTransactionTypeORDERCANCELREJECT string = "ORDER_CANCEL_REJECT"
	// OrderClientExtensionsModifyTransactionTypeORDERCLIENTEXTENSIONSMODIFY captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY"
	OrderClientExtensionsModifyTransactionTypeORDERCLIENTEXTENSIONSMODIFY string = "ORDER_CLIENT_EXTENSIONS_MODIFY"
	// OrderClientExtensionsModifyTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT captures enum value "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	OrderClientExtensionsModifyTransactionTypeORDERCLIENTEXTENSIONSMODIFYREJECT string = "ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// OrderClientExtensionsModifyTransactionTypeTRADECLIENTEXTENSIONSMODIFY captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY"
	OrderClientExtensionsModifyTransactionTypeTRADECLIENTEXTENSIONSMODIFY string = "TRADE_CLIENT_EXTENSIONS_MODIFY"
	// OrderClientExtensionsModifyTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT captures enum value "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	OrderClientExtensionsModifyTransactionTypeTRADECLIENTEXTENSIONSMODIFYREJECT string = "TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT"
	// OrderClientExtensionsModifyTransactionTypeMARGINCALLENTER captures enum value "MARGIN_CALL_ENTER"
	OrderClientExtensionsModifyTransactionTypeMARGINCALLENTER string = "MARGIN_CALL_ENTER"
	// OrderClientExtensionsModifyTransactionTypeMARGINCALLEXTEND captures enum value "MARGIN_CALL_EXTEND"
	OrderClientExtensionsModifyTransactionTypeMARGINCALLEXTEND string = "MARGIN_CALL_EXTEND"
	// OrderClientExtensionsModifyTransactionTypeMARGINCALLEXIT captures enum value "MARGIN_CALL_EXIT"
	OrderClientExtensionsModifyTransactionTypeMARGINCALLEXIT string = "MARGIN_CALL_EXIT"
	// OrderClientExtensionsModifyTransactionTypeDELAYEDTRADECLOSURE captures enum value "DELAYED_TRADE_CLOSURE"
	OrderClientExtensionsModifyTransactionTypeDELAYEDTRADECLOSURE string = "DELAYED_TRADE_CLOSURE"
	// OrderClientExtensionsModifyTransactionTypeDAILYFINANCING captures enum value "DAILY_FINANCING"
	OrderClientExtensionsModifyTransactionTypeDAILYFINANCING string = "DAILY_FINANCING"
	// OrderClientExtensionsModifyTransactionTypeRESETRESETTABLEPL captures enum value "RESET_RESETTABLE_PL"
	OrderClientExtensionsModifyTransactionTypeRESETRESETTABLEPL string = "RESET_RESETTABLE_PL"
)

// prop value enum
func (m *OrderClientExtensionsModifyTransaction) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, orderClientExtensionsModifyTransactionTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *OrderClientExtensionsModifyTransaction) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderClientExtensionsModifyTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderClientExtensionsModifyTransaction) UnmarshalBinary(b []byte) error {
	var res OrderClientExtensionsModifyTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
