// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// OrderRequest The base Order specification used when requesting that an Order be created. Each specific Order-type extends this definition.
// swagger:model OrderRequest
type OrderRequest interface{}
