// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PriceBucket A Price Bucket represents a price available for an amount of liquidity
// swagger:model PriceBucket
type PriceBucket struct {

	// The amount of liquidity offered by the PriceBucket
	Liquidity int64 `json:"liquidity,omitempty"`

	// The Price offered by the PriceBucket
	Price string `json:"price,omitempty"`
}

// Validate validates this price bucket
func (m *PriceBucket) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PriceBucket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PriceBucket) UnmarshalBinary(b []byte) error {
	var res PriceBucket
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
