// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SetTradeClientExtensionsNotFoundBody set trade client extensions not found body
// swagger:model setTradeClientExtensionsNotFoundBody
type SetTradeClientExtensionsNotFoundBody struct {

	// The code of the error that has occurred. This field may not be returned for some errors.
	ErrorCode string `json:"errorCode,omitempty"`

	// The human-readable description of the error that has occurred.
	ErrorMessage string `json:"errorMessage,omitempty"`

	// The ID of the most recent Transaction created for the Account. Only present if the Account exists.
	LastTransactionID string `json:"lastTransactionID,omitempty"`

	// The IDs of all Transactions that were created while satisfying the request. Only present if the Account exists.
	RelatedTransactionIds []string `json:"relatedTransactionIDs"`

	// trade client extensions modify reject transaction
	TradeClientExtensionsModifyRejectTransaction *TradeClientExtensionsModifyRejectTransaction `json:"tradeClientExtensionsModifyRejectTransaction,omitempty"`
}

// Validate validates this set trade client extensions not found body
func (m *SetTradeClientExtensionsNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRelatedTransactionIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTradeClientExtensionsModifyRejectTransaction(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetTradeClientExtensionsNotFoundBody) validateRelatedTransactionIds(formats strfmt.Registry) error {

	if swag.IsZero(m.RelatedTransactionIds) { // not required
		return nil
	}

	return nil
}

func (m *SetTradeClientExtensionsNotFoundBody) validateTradeClientExtensionsModifyRejectTransaction(formats strfmt.Registry) error {

	if swag.IsZero(m.TradeClientExtensionsModifyRejectTransaction) { // not required
		return nil
	}

	if m.TradeClientExtensionsModifyRejectTransaction != nil {

		if err := m.TradeClientExtensionsModifyRejectTransaction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tradeClientExtensionsModifyRejectTransaction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SetTradeClientExtensionsNotFoundBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetTradeClientExtensionsNotFoundBody) UnmarshalBinary(b []byte) error {
	var res SetTradeClientExtensionsNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
