// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SetTradeClientExtensionsOKBody set trade client extensions o k body
// swagger:model setTradeClientExtensionsOKBody
type SetTradeClientExtensionsOKBody struct {

	// The ID of the most recent Transaction created for the Account
	LastTransactionID string `json:"lastTransactionID,omitempty"`

	// The IDs of all Transactions that were created while satisfying the request.
	RelatedTransactionIds []string `json:"relatedTransactionIDs"`

	// trade client extensions modify transaction
	TradeClientExtensionsModifyTransaction *TradeClientExtensionsModifyTransaction `json:"tradeClientExtensionsModifyTransaction,omitempty"`
}

// Validate validates this set trade client extensions o k body
func (m *SetTradeClientExtensionsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRelatedTransactionIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTradeClientExtensionsModifyTransaction(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SetTradeClientExtensionsOKBody) validateRelatedTransactionIds(formats strfmt.Registry) error {

	if swag.IsZero(m.RelatedTransactionIds) { // not required
		return nil
	}

	return nil
}

func (m *SetTradeClientExtensionsOKBody) validateTradeClientExtensionsModifyTransaction(formats strfmt.Registry) error {

	if swag.IsZero(m.TradeClientExtensionsModifyTransaction) { // not required
		return nil
	}

	if m.TradeClientExtensionsModifyTransaction != nil {

		if err := m.TradeClientExtensionsModifyTransaction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tradeClientExtensionsModifyTransaction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SetTradeClientExtensionsOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetTradeClientExtensionsOKBody) UnmarshalBinary(b []byte) error {
	var res SetTradeClientExtensionsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
