// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TradeSpecifier The identification of a Trade as referred to by clients
// swagger:model TradeSpecifier
type TradeSpecifier string

// Validate validates this trade specifier
func (m TradeSpecifier) Validate(formats strfmt.Registry) error {
	return nil
}
