// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TradeID The Trade's identifier, unique within the Trade's Account.
// swagger:model TradeID
type TradeID string

// Validate validates this trade ID
func (m TradeID) Validate(formats strfmt.Registry) error {
	return nil
}
