// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TradeSummary The summary of a Trade within an Account. This representation does not provide the full details of the Trade's dependent Orders.
// swagger:model TradeSummary
type TradeSummary struct {

	// The average closing price of the Trade. Only present if the Trade has been closed or reduced at least once.
	AverageClosePrice string `json:"averageClosePrice,omitempty"`

	// client extensions
	ClientExtensions *ClientExtensions `json:"clientExtensions,omitempty"`

	// The date/time when the Trade was fully closed. Only provided for Trades whose state is CLOSED.
	CloseTime string `json:"closeTime,omitempty"`

	// The IDs of the Transactions that have closed portions of this Trade.
	ClosingTransactionIds []string `json:"closingTransactionIDs"`

	// The number of units currently open for the Trade. This value is reduced to 0.0 as the Trade is closed.
	CurrentUnits string `json:"currentUnits,omitempty"`

	// The financing paid/collected for this Trade.
	Financing string `json:"financing,omitempty"`

	// The Trade's identifier, unique within the Trade's Account.
	ID string `json:"id,omitempty"`

	// The initial size of the Trade. Negative values indicate a short Trade, and positive values indicate a long Trade.
	InitialUnits string `json:"initialUnits,omitempty"`

	// The Trade's Instrument.
	Instrument string `json:"instrument,omitempty"`

	// The date/time when the Trade was opened.
	OpenTime string `json:"openTime,omitempty"`

	// The execution price of the Trade.
	Price string `json:"price,omitempty"`

	// The total profit/loss realized on the closed portion of the Trade.
	RealizedPL string `json:"realizedPL,omitempty"`

	// The current state of the Trade.
	State string `json:"state,omitempty"`

	// ID of the Trade's Stop Loss Order, only provided if such an Order exists.
	StopLossOrderID string `json:"stopLossOrderID,omitempty"`

	// ID of the Trade's Take Profit Order, only provided if such an Order exists.
	TakeProfitOrderID string `json:"takeProfitOrderID,omitempty"`

	// ID of the Trade's Trailing Stop Loss Order, only provided if such an Order exists.
	TrailingStopLossOrderID string `json:"trailingStopLossOrderID,omitempty"`

	// The unrealized profit/loss on the open portion of the Trade.
	UnrealizedPL string `json:"unrealizedPL,omitempty"`
}

// Validate validates this trade summary
func (m *TradeSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientExtensions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateClosingTransactionIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TradeSummary) validateClientExtensions(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientExtensions) { // not required
		return nil
	}

	if m.ClientExtensions != nil {

		if err := m.ClientExtensions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clientExtensions")
			}
			return err
		}
	}

	return nil
}

func (m *TradeSummary) validateClosingTransactionIds(formats strfmt.Registry) error {

	if swag.IsZero(m.ClosingTransactionIds) { // not required
		return nil
	}

	return nil
}

var tradeSummaryTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OPEN","CLOSED","CLOSE_WHEN_TRADEABLE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tradeSummaryTypeStatePropEnum = append(tradeSummaryTypeStatePropEnum, v)
	}
}

const (
	// TradeSummaryStateOPEN captures enum value "OPEN"
	TradeSummaryStateOPEN string = "OPEN"
	// TradeSummaryStateCLOSED captures enum value "CLOSED"
	TradeSummaryStateCLOSED string = "CLOSED"
	// TradeSummaryStateCLOSEWHENTRADEABLE captures enum value "CLOSE_WHEN_TRADEABLE"
	TradeSummaryStateCLOSEWHENTRADEABLE string = "CLOSE_WHEN_TRADEABLE"
)

// prop value enum
func (m *TradeSummary) validateStateEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, tradeSummaryTypeStatePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TradeSummary) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TradeSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TradeSummary) UnmarshalBinary(b []byte) error {
	var res TradeSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
