// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UnitsAvailableDetails Representation of many units of an Instrument are available to be traded for both long and short Orders.
// swagger:model UnitsAvailableDetails
type UnitsAvailableDetails struct {

	// The units available for long Orders.
	Long string `json:"long,omitempty"`

	// The units available for short Orders.
	Short string `json:"short,omitempty"`
}

// Validate validates this units available details
func (m *UnitsAvailableDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UnitsAvailableDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnitsAvailableDetails) UnmarshalBinary(b []byte) error {
	var res UnitsAvailableDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
