// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// UserInfoExternal A representation of user information, as available to external (3rd party) clients.
// swagger:model UserInfoExternal
type UserInfoExternal struct {

	// Flag indicating if the the user's Accounts adhere to FIFO execution rules.
	FIFO bool `json:"FIFO,omitempty"`

	// The country that the user is based in.
	Country string `json:"country,omitempty"`

	// The user's OANDA-assigned user ID.
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this user info external
func (m *UserInfoExternal) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *UserInfoExternal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserInfoExternal) UnmarshalBinary(b []byte) error {
	var res UserInfoExternal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
